[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "C4"]

[tool.ruff.lint.isort]
known-first-party = ["auth", "config", "db", "errors", "routes"]